#!/bin/sh

from_branch=mix

cur_hash=$(git log -n1 --format="%H")
cur_branch=$(git symbolic-ref HEAD 2>/dev/null)
if [ ".$cur_branch" == "." ]; then
    echo "not on a branch"
    exit 1
fi

head_hash=$(git log -n1 --format="%H" HEAD)
tree_hash=$(git cat-file -p $from_branch | head -n1 | awk '{print $2}')

echo make new commit of $cur_branch with tree $tree_hash

new_hash=$(echo "dev\n\nx-update-from: $from_branch $cur_hash" | git commit-tree $tree_hash -p $head_hash)
git merge --ff-only $new_hash

# to re-edit commit message
git commit --amend
