#!/bin/sh

branches=
branches="$branches $(git branch | awk '{print $NF}' | grep "^f\.")"
branches="$branches $(git branch | awk '{print $NF}' | grep "^t\.")"
branches="$branches $(git branch | awk '{print $NF}' | grep "^snp\.")"

echo $branches

git merge \
    --no-edit \
    --commit \
    --no-ff \
    $branches \
    && ./_script/update \
    && git tag -f mixdoc

